version: "3.8"
services:
  # Database
  postgres:
    container_name: BIPdb
    image: postgres:16.4
    env_file:
      - /app/exe_dumper/.env-database
    volumes:
      - database_dbdata:/app/database/data/postgres
    ports:
      - "5432:5432"
    restart: always
  
  # Main app
  exe_dumper:
    container_name: exe_dump
    image: exe_dumper:1
    ports:
      - "80:5000"
    restart: always

    # Evil twin
    evil_dumper:
      container_name: evil_dump
      image: evil_dumper:1
      ports:
        - "8080:5000"
      volumes:
        - /app/exe_dumper/evil_twin:/app/evil_info
      restart: always

volumes:
  database_dbdata:
    external: true
